[project]
name = "cdl-misinfo-dataset-eval"
version = "0.1.0"
description = "Tools for automated evaluation of CDL Misinfo Dataset"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "backoff",
    "datasets",
    "openai",
    "tqdm",
    "scikit-learn",
    "isort",
    "black",
    "nltk",
]
